NAME: 'QCR.CLIP.AE.ROCO.VQASLAKE.16batchsize.200epoch.withTFIDF.nondeterministic'
OUTPUT_DIR: './output/qcr/clip_ae/roco/VQASLAKE_normal'
METHOD: 'normal'
CPU_MODE: False
SEED: 88

DATASET:
  DATASET: "SLAKE"
  DATA_DIR: "./data/data_slake"
  DATA_TYPE: 'jpg'

LOSS:
  LOSS_TYPE: 'BCELogits'

TRAIN:
  BATCH_SIZE: 16 
  N_EPOCH: 200
  NUM_WORKERS: 2 
  RESUME: False 
  INPUT_SNAPSHOT: "" 
  OPTIMIZER:
    TYPE: 'ADAMX'
    BASE_LR: 1e-3
    MOMENTUM_CNN: 0.05
    EPS_CNN: 1e-5
  ACTIVATION: 'relu'
  DROPOUT: 0.5
  ATTENTION:
    MODE: 'BAN'
    GLIMPSE: 10
    USE_COUNTER: False
    NUM_STACKS: 2    ## For SAN
  QUESTION:
    RNN: 'GRU'
    LENGTH: 12
    TFIDF: True
    CAT: True
    HID_DIM: 1024   ## Dim of joint semantic features
  VISION:
    V_DIM: 576    ## Visual input dim
    AUTOENCODER: True 
    AE_PATH: "pretrained_ae.pth"
    AE_ALPHA: 0.001
    MAML: False
    CLIP: True
    CLIP_PATH: "./data/models/PubMedCLIP_ViT32.pth"
    OTHER_MODEL: False


TRANSFORMS:
  TRAIN_TRANSFORMS: ("random_resized_crop", "random_horizontal_flip")
  TEST_TRANSFORMS: ("shorter_resize_for_crop", "center_crop")
  
TEST:
  BATCH_SIZE: 8 
  NUM_WORKERS: 4
  MODEL_FILE: './output/qcr/clip_ae/roco/VQASLAKE_normal/QCR.CLIP.AE.ROCO.VQASLAKE.16batchsize.200epoch.withTFIDF.nondeterministic/62_best.pth'
  RESULT_DIR: './output/qcr/test/normal'